# Generated by Django 4.2.7 on 2023-12-01 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gstin', models.CharField(max_length=1000)),
                ('Address', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('gstin', models.CharField(max_length=1000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('email_verified', models.BooleanField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField()),
                ('invoice_id', models.CharField(max_length=100)),
                ('tax', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('subtotal', models.CharField(max_length=10000000)),
                ('currency', models.CharField(max_length=100000)),
                ('due_date', models.DateField()),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.IntegerField()),
                ('amount_received', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE')], max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.clients')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.companies')),
            ],
        ),
        migrations.CreateModel(
            name='taxes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('percent', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.CharField(blank=True, max_length=100000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_supueruser', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_access',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_rights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.companies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=1000)),
                ('total_amount', models.CharField(max_length=10000)),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt_no', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.clients')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.companies')),
            ],
        ),
        migrations.CreateModel(
            name='salesItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=1000)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sales')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE')], max_length=1000)),
                ('amount', models.CharField(max_length=10000)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.transactions')),
            ],
        ),
        migrations.AddField(
            model_name='companies',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customers'),
        ),
        migrations.AddField(
            model_name='clients',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.companies'),
        ),
    ]
