# Generated by Django 4.2.7 on 2023-12-03 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='client_unique',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='companies',
            name='company_unique',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_unique',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='sale_unique',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
