# Generated by Django 4.2.7 on 2023-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_clients_client_unique_companies_company_unique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tax',
        ),
        migrations.AddField(
            model_name='sales',
            name='discountAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='discountPercent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='taxAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='taxPercent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
