# Generated by Django 4.2.7 on 2023-12-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_sales_discount_remove_sales_tax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='discountAmount',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='discountPercent',
            new_name='discount_percent',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='taxAmount',
            new_name='tax_amount',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='taxPercent',
            new_name='tax_percent',
        ),
        migrations.AlterField(
            model_name='sales',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
