# Generated by Django 4.2.7 on 2023-12-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_discountamount_sales_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
