# Generated by Django 4.2.7 on 2023-12-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_sales_front_random_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='taxes',
        ),
        migrations.DeleteModel(
            name='units',
        ),
    ]
