# Generated by Django 4.2.7 on 2023-12-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_delete_taxes_delete_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitem',
            old_name='item',
            new_name='name',
        ),
    ]
