# Generated by Django 4.2.7 on 2023-12-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_item_salesitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='amount_in_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
