# Generated by Django 4.2.7 on 2023-12-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_sales_amount_in_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
