# Generated by Django 4.2.7 on 2023-12-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_qty_salesitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='Address',
            new_name='address',
        ),
    ]
