# Generated by Django 4.2.7 on 2023-12-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_sales_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.sales'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('UPI', 'UPI'), ('RTGS/NEFT', 'RTGS/NEFT')], max_length=1000),
        ),
        migrations.DeleteModel(
            name='transactions',
        ),
    ]
