# Generated by Django 4.2.7 on 2023-12-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_sales_amount_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='payment_type',
        ),
    ]
